# Generated by Django 5.0 on 2024-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Image URL'),
        ),
    ]
